check:
  - thoth-build
build:
  base-image: "quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.28.0"
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: manage-dependencies-tutorial
  registry-secret: thoth-station-thoth-pusher-secret
